name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REDIS_URL: redis://redis:6379/0

on:
  pull_request:
    branches: ["master", "main", "develop"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main", "develop"]
    paths-ignore: ["docs/**"]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel setuptools invoke rich
          invoke project.install-tools
          invoke project.install-requirements

      - name: Run linters
        run: inv linters.all

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Build the Stack
        run:  docker-compose build

      - name: Run DB Migrations
        run:  docker-compose run --rm server python manage.py migrate

      - name: Run Django Tests
        run:  docker-compose run django pytest

      - name: Tear down the Stack
        run:  docker-compose down
